@echo off
echo Starting Life Analytics 2.0...

echo Starting Backend...
start "Backend" cmd /c "cd backend && "C:\Users\HP\.m2\wrapper\dists\apache-maven-3.9.11\d6d3cbd4012d4c1d840e93277aca316c\bin\mvn.cmd" spring-boot:run"

echo Waiting for Backend to initialize...
timeout /t 10

echo Starting Frontend...
start "Frontend" cmd /c "cd frontend && streamlit run app.py"

echo All services started!
